;;; loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from dm-ai.el

(register-definition-prefixes "dm-ai" '("dm-"))


;;; Generated autoloads from dm-completion.el

(autoload 'dm-search-for-this-dwim "dm-completion"
"Search the current visual selection, or symbol-at-point if no selection.
Search in the current project if one is active, otherwise search the current
directory hierarchy.

(fn &optional BEG END)" t)


;;; Generated autoloads from dm-editing.el

(autoload 'dm-tab-dwim "dm-editing"
"Smart TAB: advance Tempel field, expand snippet, or indent." t)
(register-definition-prefixes "dm-editing" '("dm-text-"))


;;; Generated autoloads from dm-env.el

(register-definition-prefixes "dm-env" '("dm-designated-tty-daemon-p"))


;;; Generated autoloads from dm-evil-text.el

(autoload 'dm-evil-text-setup "dm-evil-text"
"Install Daymacs Evil text objects and sort bindings.")
(register-definition-prefixes "dm-evil-text" '("dm-evil-text-"))


;;; Generated autoloads from dm-files.el

(autoload 'dm-open-config-new-tab "dm-files"
"Open the Emacs init.el file in a new tab." t)
(autoload 'dm-find-in-home--refresh-cache "dm-files"
"Asynchronously refresh `dm-find-in-home--dir-cache'.
Fires fd in a subprocess; stores results when it exits cleanly. Safe to
call repeatedly -- an in-flight refresh is cancelled before a new one starts.")
(autoload 'dm-find-in-home "dm-files"
"Two-stage `fd' selection for directory and file within $HOME.
Stage 1 reads from `dm-find-in-home--dir-cache' when populated, falling
back to a synchronous fd run on the first invocation after startup." t)
(autoload 'dm-directory-open "dm-files"
"Open the directory of the current buffer's file in Finder." t)
(autoload 'dm-directory-open-project "dm-files"
"Open the current project root, falling back to the current directory.
This never prompts for a project." t)
(autoload 'dm-file-open "dm-files"
"Open the current buffer's file with the default or configured app.

Uses `dm-file-open-apps' to choose an app by filename regexp.
Falls back to macOS `open'." t)
(autoload 'dm-copy-file-path "dm-files"
"Copy the current buffer file path with home abbreviated as `~'.

If the file is not under the user's home directory, report nil." t)
(autoload 'dm-copy-file-abspath "dm-files"
"Copy the absolute path of the current buffer's file." t)
(autoload 'dm-copy-file-project-path "dm-files"
"Copy the current buffer file path relative to the project root.

If the file is not inside the current project, report nil." t)
(autoload 'dm-copy-file-path-dwim "dm-files"
"Copy the most useful path for the current buffer file.

Preference order:

1. Project-relative path.
2. Home-abbreviated path.
3. Absolute path.

If the buffer has no file, report that instead." t)
(autoload 'dm-delete-this-file "dm-files"
"Delete the current buffer's file.

(fn &optional PATH)" t)
(autoload 'dm-project-discover-projects "dm-files"
"Discover Git projects under DIRECTORY and remember them with project.el.
DIRECTORY defaults to the user's home directory.

(fn &optional DIRECTORY)" t)
(register-definition-prefixes "dm-files" '("dm-"))


;;; Generated autoloads from dm-langs.el

(autoload 'dm-treesit-install-all-languages "dm-langs"
"Install missing Tree-sitter grammars.

Normally install grammars from `dm-treesit-language-source-alist'.

With prefix argument USE-TREESIT-AUTO, install grammars known to
`treesit-auto' using `treesit-auto--build-treesit-source-alist'
and `treesit-auto-langs'.

(fn &optional USE-TREESIT-AUTO)" t)
(register-definition-prefixes "dm-langs" '("dm-"))


;;; Generated autoloads from dm-lisp.el

(register-definition-prefixes "dm-lisp" '("dm-e"))


;;; Generated autoloads from dm-log.el

(register-definition-prefixes "dm-log" '("dm-log"))


;;; Generated autoloads from dm-magit.el

(autoload 'dm-git-commit-insert-pending-generated-message "dm-magit"
"Insert pending generated commit message into the current commit buffer.")
(autoload 'dm-magit-commit-generate "dm-magit"
"Generate a commit message, then open Magit's commit buffer." t)
(autoload 'dm-magit-display-buffer-fn "dm-magit"
"Display Magit BUFFER with less window churn.
This follows Doom's strategy closely enough for the status-to-commit
transition: reuse the current window for most non-diff buffers and keep
process buffers below the selected window.

(fn BUFFER)")
(autoload 'dm-git-commit-disable-completion "dm-magit"
"Disable dabbrev in Git commit message buffers.")
(register-definition-prefixes "dm-magit" '("dm-"))


;;; Generated autoloads from dm-popup-quit.el

(autoload 'dm-quit-or-close-popup "dm-popup-quit"
"Close a visible popup window, or otherwise run `keyboard-quit'.
A popup window is any non-selected visible window whose buffer name is listed
in `dm-quit-or-close-popup-buffer-names' or starts with one of
`dm-quit-or-close-popup-buffer-prefixes'." t)
(register-definition-prefixes "dm-popup-quit" '("dm-quit-or-close-popup-"))


;;; Generated autoloads from dm-repl.el

(autoload 'dm-repl-start-or-pop "dm-repl"
"Start or pop to the REPL appropriate for the current buffer." t)
(autoload 'dm-repl-eval-region "dm-repl"
"Evaluate region START END in the language-appropriate REPL.

(fn START END)" t)
(autoload 'dm-repl-eval-line "dm-repl"
"Evaluate the current line in the language-appropriate REPL." t)
(autoload 'dm-repl-eval-buffer "dm-repl"
"Evaluate the current buffer in the language-appropriate REPL." t)
(autoload 'dm-repl-eval-dwim "dm-repl"
"Evaluate active region, current code cell, or current line." t)
(autoload 'dm-repl-eval-cell "dm-repl"
"Evaluate the current code cell." t)
(autoload 'dm-repl-next-cell "dm-repl"
"Move to the next code cell." t)
(autoload 'dm-repl-previous-cell "dm-repl"
"Move to the previous code cell." t)
(autoload 'dm-repl-check-dwim "dm-repl"
"Run the fastest project check for the current language." t)
(autoload 'dm-repl-test-dwim "dm-repl"
"Run the nearest or current-buffer test for the current language." t)
(autoload 'dm-repl-test-all "dm-repl"
"Run all tests for the current language." t)
(autoload 'dm-repl-local-keybindings "dm-repl"
"Install tight-loop local bindings and mode helpers in programming buffers.")
(register-definition-prefixes "dm-repl" '("dm-"))


;;; Generated autoloads from dm-session.el

(autoload 'dm-restart-emacs-no-restore "dm-session"
"Restart Emacs without restoring the desktop." t)
(autoload 'dm-restart-emacs-and-restore "dm-session"
"Save desktop and restart Emacs." t)


;;; Generated autoloads from dm-test-toggle.el

(autoload 'dm-toggle-test-implementation "dm-test-toggle"
"Toggle between implementation and test file using project.el." t)
(register-definition-prefixes "dm-test-toggle" '("dm-"))


;;; Generated autoloads from dm-text.el

(autoload 'dm-text-latex-wrap-as-math "dm-text"
"Wrap selected text, or text around point, in LaTeX math delimiters.
With DISPLAYMODE-P, use display math delimiters.

(fn DISPLAYMODE-P)" t)
(autoload 'dm-text-latex-wrap-as-math-display "dm-text"
"Wrap selected text, or text around point, in LaTeX display math delimiters." t)
(autoload 'dm-text-latex-wrap-as-frac "dm-text"
"Wrap selected text, or text around point, in a LaTeX fraction command." t)
(autoload 'dm-text-latex-wrap-as-boxed "dm-text"
"Wrap selected text, or text around point, in a LaTeX boxed command." t)
(autoload 'dm-text-latex-wrap-as-si "dm-text"
"Format the selected text as a LaTeX SI unit expression." t)
(autoload 'dm-text-latex-evaluate-selection "dm-text"
"Evaluate selected LaTeX-flavored math and replace it with the result." t)
(autoload 'dm-text-make-bold "dm-text"
"Format selected text, or text around point, as bold." t)
(autoload 'dm-text-make-italic "dm-text"
"Format selected text, or text around point, as italic." t)
(autoload 'dm-text-make-underlined "dm-text"
"Format selected text, or text around point, as underlined." t)
(autoload 'dm-text-make-strikethrough "dm-text"
"Format selected text, or text around point, as strikethrough." t)
(register-definition-prefixes "dm-text" '("dm-text-"))


;;; Generated autoloads from dm-tty.el

(register-definition-prefixes "dm-tty" '("dm-pb"))


;;; Generated autoloads from dm-ui.el

(autoload 'dm-wrapping-enable "dm-ui"
"Enable visual wrapping in the current buffer." t)
(autoload 'dm-wrapping-disable "dm-ui"
"Disable visual wrapping in the current buffer." t)
(autoload 'dm-wrapping-toggle "dm-ui"
"Toggle visual line wrapping in the current buffer." t)
(register-definition-prefixes "dm-ui" '("dm-"))


;;; Generated autoloads from dm-vcs.el

(register-definition-prefixes "dm-vcs" '("dm-"))


;;; Generated autoloads from dm-window.el

(autoload 'dm-delete-window-dwim "dm-window"
"Delete window, do what I mean.
Close tab if sole window in tab, close frame if multiple frames exist,
otherwise kill Emacs." t)
(register-definition-prefixes "dm-window" '("dm-window-"))


;;; Generated autoloads from dm-xdg.el

(register-definition-prefixes "dm-xdg" '("dm-xdg-"))


;;; Generated autoloads from dm-core.el

(register-definition-prefixes "dm-core" '("dm-core-global-minor-modes"))

;;; End of scraped data

(provide 'loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; loaddefs.el ends here
